"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const SeparateChaining_1 = __importDefault(require("./SeparateChaining"));
const testMap = new SeparateChaining_1.default(10);
console.log(testMap);
console.log(testMap.hash('hello'));
console.log(testMap.hash('mello'));
testMap.assign('hello', 'kitty');
console.log(testMap);
console.log(testMap.hashmap[1]);
testMap.assign('mello', 'schmitty');
console.log(testMap.hashmap);
console.log(testMap.deleteNode('hello', 'kitty'));
console.log(testMap.deleteNode('hello', 'pity'));
console.log(testMap.deleteNode('elbow', 'city'));
console.log(testMap.hashmap[1].head);
testMap.assign('yellow', 'witty');
console.log(testMap.hashmap);
console.log(testMap.deleteNode('yellow', 'witty'));
console.log(testMap.clearBucket('yellow'));
console.log(testMap.clearBucket('cord'));
console.log(testMap.hashmap);
